### PR TITLE
fix: prevent merges to have cycles and infinite recursion fixes #100

### LINKED ISSUE #100: warn when a merge source refers to itself
I kept getting massive amounts of logs (gigabytes every few days), finally narrowed it down to goeland, and turned off debug logging, thinking the problem was solved. But I wasn't getting any emails from a particular pipe and I was confused by that. Turns out I had accidentally included the merge source in its own set of sources, causing an infinite loop. All the other pipes ran as expected, which was why I wasn't tipped off sooner.

It could be good to include a check for self-reference like that. Obviously you could still come up with contrived examples to produce infinite looping, like by having two merge sources reference each other, but this would warn users quickly if they've made a simple mistake. Thoughts?

### PR DESCRIPTION
**Pull request by slurdge**

### CODE REVIEW

File: internal/goeland/fetch/source.go [hunk 1]
```diff
@@ -11,10 +11,13 @@ import (
 )
 
 // FetchSource retrieves a source from either a feed, imgur or other sub-sources
-func FetchSource(config config.Provider, sourceName string) (*goeland.Source, error) {
+func FetchSource(config config.Provider, sourceName string, parents []string) (*goeland.Source, error) {
 	if !config.IsSet(fmt.Sprintf("sources.%s", sourceName)) {
 		return nil, fmt.Errorf("cannot find source: %s", sourceName)
 	}
+	if filters.StringInSlice(strings.ToLower(sourceName), parents) {
+		return nil, fmt.Errorf("source: %s has already be seen, preventing cycle", sourceName)
```
Comment (sweenu) [inline internal/goeland/fetch/source.go:19]: "source: %s has already be**en** seen, preventing cycle"

But I think a better error message for the end user would be something like:
"there seems to be a cycle in your configuration. Make sure no "merge" source is referencing itself."

It gives out the information that there is a problem with the user's config and doesn't induce the user into thinking the `source %s` is the problem because it's not, it just happens to be the first source that was fetched twice.

Comment (kylrth) [reply internal/goeland/fetch/source.go:19]: Agreed

**Comment by slurdge** [comment]
I agree it's better, I will change it but it will be in next version :)
